#!/bin/sh
cd /boot/home/projects/FontMonkey/PackagingFolder
package create -b fontmonkey_0.1.2-11_gcc2.hpkg
sleep 0.5
package add fontmonkey_0.1.2-11_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "A font manager for Haiku with Package Management" fontmonkey_0.1.2-11_gcc2.hpkg
becopy fontmonkey_0.1.2-11_gcc2.hpkg "/Storage/Haiku/My ports"
mv fontmonkey_0.1.2-11_gcc2.hpkg /boot/home/projects/repo
sync
